'use client';

import { motion, Variants } from "framer-motion";
import { Server, Cpu, Lock, Network, Database, Shield, ArrowRight, Activity, Terminal as TerminalIcon, Building2, ArrowLeft } from "lucide-react";
import { useState, useEffect } from "react";
import Link from "next/link";
import Image from "next/image";

// AI-Generated Enterprise Case Studies reflecting the new "Systems Architecture" context
const clients = [
    {
        name: "Apple",
        logo: "/clients/apple.svg",
        title: "Global Deployment Layer Tracking",
        caseStudy: "Developed deterministic on-device diagnostic frameworks and spatial engagement flows (SPEAR / Hubble). Bridged physical hardware with strictly segregated serverless cloud infrastructure across global enterprise campuses, handling massive concurrent telemetry."
    },
    {
        name: "Amazon",
        logo: "/clients/amazon.svg",
        title: "High-Scale Conversational Logistics",
        caseStudy: "Designed edge-native conversational bridges for warehouse automation. Optimized low-latency voice command inference models for immediate logistical routing, executing within stringent microsecond SLA constraints."
    },
    {
        name: "Walmart",
        logo: "/clients/walmart.svg",
        title: "Distributed Retail Systems",
        caseStudy: "Architected global logistics tracking systems capable of ingesting millions of synchronized telemetry requests per second. Migrated legacy inventory DBs to predictive ML pipelines to preempt supply chain bottlenecks."
    },
    {
        name: "Nike",
        logo: "/clients/nike.svg",
        title: "Real-Time Engagement Infrastructure",
        caseStudy: "Engineered scalable retail engagement grids. Synchronized local store Edge nodes with massive federated networks to process high-throughput transactional and behavioral data during high-stress peak events."
    },
    {
        name: "Southwest Airlines",
        logo: "/clients/southwest airlines.svg",
        title: "Flight Logistics Automation",
        caseStudy: "Developed predictive routing and crew scheduling optimization systems. Leveraged advanced operations research algorithms paired with real-time API integrations to minimize delay propagation across the national grid."
    },
    {
        name: "Verizon",
        logo: "/clients/verizon.svg",
        title: "Network Latency & Signal Prediction",
        caseStudy: "Built deep neural networks to predict cell tower congestion and auto-scale bandwidth allocations. Processed continuous streams of 5G telemetry data to ensure minimal packet loss for enterprise clients."
    },
    {
        name: "GE",
        logo: "/clients/ge.svg",
        title: "Industrial IoT Edge Inference",
        caseStudy: "Deployed optimized ML models directly onto heavy machinery sensors. Enabled real-time anomaly detection and predictive maintenance alerts without relying on continuous cloud connectivity."
    },
    {
        name: "Intuit",
        logo: "/clients/intuit.svg",
        title: "Financial LLM Data Structuring",
        caseStudy: "Architected secure data pipelines to parse unstructured financial records. Applied semantic search and Named Entity Recognition to automate tax categorization with ultra-high accuracy and absolute privacy compliance."
    },
    {
        name: "Oracle",
        logo: "/clients/oracle.svg",
        title: "Enterprise DB Optimization",
        caseStudy: "Integrated autonomous machine learning techniques to monitor query performance at scale. Built internal tooling that dynamically adjusted database indexing based on live traffic patterns."
    },
    {
        name: "Chase",
        logo: "/clients/chase.svg",
        title: "Fraud Detection Neural Architectures",
        caseStudy: "Designed graph-based neural networks to identify complex money-laundering topologies. Achieved sub-50ms transaction verification latency, safeguarding massive volumes of daily financial operations."
    },
    {
        name: "DirecTV",
        logo: "/clients/directv.svg",
        title: "Real-Time Content Analytics",
        caseStudy: "Engineered high-throughput streaming telemetry pipelines. Utilized collaborative filtering models to power real-time content recommendation engines for millions of simultaneous viewers."
    },
    {
        name: "Hyundai",
        logo: "/clients/hyundai.svg",
        title: "Connected Vehicle Telemetry",
        caseStudy: "Developed secure OTA (Over-The-Air) model update protocols. Processed continuous sensor fusion data generated by autonomous driving subsystems to improve fleet-wide object detection algorithms."
    },
    {
        name: "Volkswagen",
        logo: "/clients/volkswagen.svg",
        title: "Manufacturing Defect Computer Vision",
        caseStudy: "Deployed high-speed manufacturing line inspection systems. Utilized quantized Vision Transformers to detect micro-fractures in structural components with better-than-human reliability."
    },
    {
        name: "Panavision",
        logo: "/clients/panavision.svg",
        title: "Lens Calibration Automation",
        caseStudy: "Automated the precision calibration of cinematic lenses using computer vision. Built software that mapped chromatic aberration across complex glass elements to feed manufacturing corrections."
    },
    {
        name: "Technicolor",
        logo: "/clients/technicolor.svg",
        title: "Visual FX Rendering Pipelines",
        caseStudy: "Optimized massive GPU render farm allocations using predictive modeling. Reduced rendering bottlenecks for high-bandwidth cinematic sequences through intelligent distributed computing."
    },
    {
        name: "CBS",
        logo: "/clients/cbs.svg",
        title: "High-Throughput Media Distribution",
        caseStudy: "Architected resilient content delivery networks (CDNs) capable of handling unpredictable traffic spikes during live broadcast events. Implemented dynamic bitrate scaling to guarantee stream integrity."
    },
    {
        name: "KornFerry",
        logo: "/clients/kornferry.svg",
        title: "Applied NLP for Organizational Simulation",
        caseStudy: "Built sophisticated natural language processing tools to analyze executive communication patterns. Created simulated leadership scenarios powered by predictive behavioral models."
    },
    {
        name: "Vance and Hines",
        logo: "/clients/vance and hines.svg",
        title: "BLE 5.4 Edge Sensor Inference",
        caseStudy: "Developed low-latency Bluetooth Low Energy (BLE) bridges connecting high-performance motorcycle engine control units to mobile analytics dashboards for real-time race tuning."
    },
    {
        name: "Submission",
        logo: "/clients/submission.svg",
        title: "Multilingual Neural Intelligence",
        caseStudy: "Engineered entirely offline cross-lingual deterministic retrieval systems. Parsed massive ancient theological corpora using custom multi-modal embedding architectures for absolute fidelity."
    }
];

export default function SolutionsPage() {
    // Animation variants for smooth list staggered entrance
    const containerVariants: Variants = {
        hidden: { opacity: 0 },
        visible: {
            opacity: 1,
            transition: { staggerChildren: 0.15, delayChildren: 0.1 }
        }
    };

    const cardVariants: Variants = {
        hidden: { opacity: 0, y: 30 },
        visible: {
            opacity: 1,
            y: 0,
            transition: { type: "spring", stiffness: 60, damping: 20 }
        }
    };

    return (
        <div className="relative flex min-h-screen flex-col overflow-x-hidden bg-[#09090b] text-slate-100 antialiased font-sans">
            <section className="px-6 py-24 lg:py-32 relative z-10 max-w-6xl mx-auto w-full">
                <Link href="/" className="inline-flex items-center gap-2 text-sm text-zinc-400 hover:text-emerald-400 mb-12 transition-colors">
                    <ArrowLeft className="w-4 h-4" /> Back to Home
                </Link>

                {/* Enterprise Offerings Header */}
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.8 }}
                    className="mb-16"
                >
                    <span className="text-xs font-bold uppercase tracking-[0.2em] text-emerald-400 mb-4 block">Enterprise Offerings</span>
                    <h1 className="text-4xl md:text-6xl font-extrabold tracking-tight text-white mb-6">
                        Physical Intelligence for Tier-1 Infrastructure.
                    </h1>
                    <p className="text-xl text-zinc-400 leading-relaxed max-w-4xl border-l-2 border-emerald-500/50 pl-6 mb-16">
                        We provide enterprise-grade solutions for the most complex physical intelligence challenges, guaranteeing sub-millisecond latency and absolute data sovereignty through on-device edge deployments.
                    </p>
                </motion.div>

                {/* Solutions Grid */}
                <motion.div
                    variants={containerVariants}
                    initial="hidden"
                    animate="visible"
                    className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 relative z-10"
                >
                    {/* Audit & Feasibility Validation */}
                    <motion.div variants={cardVariants} className="group flex flex-col p-8 rounded-2xl bg-[#0a0a0c] border border-white/5 hover:border-emerald-500/30 transition-all duration-500 h-full relative overflow-hidden shadow-[0_0_20px_rgba(0,0,0,0.5)]">
                        <div className="absolute top-0 right-0 w-32 h-32 bg-emerald-500/5 blur-[40px] rounded-full group-hover:bg-emerald-500/10 transition-colors duration-500"></div>
                        <div className="p-3 bg-zinc-900 border border-zinc-800 rounded-lg w-fit mb-6 relative z-10">
                            <Activity className="w-6 h-6 text-emerald-400" />
                        </div>
                        <h3 className="text-xl font-bold text-white mb-3 tracking-tight relative z-10">Infrastructure Audit & Feasibility Validation</h3>
                        <p className="text-zinc-400 text-sm leading-relaxed mb-6 flex-1 relative z-10">
                            Before any tensor is computed, our engineering team executes a deep diagnostic of your existing operational topography. We evaluate your on-premise compute availability, legacy cloud dependency overhead, and viable edge capacities (Nvidia Jetsons, Apple Silicon, or custom TPUs) hosting our inference engines. This phase mathematically structures the constraints required to achieve sub-millisecond, real-time latency.
                        </p>
                        <div className="mt-auto pt-4 border-t border-white/5 relative z-10">
                            <ul className="space-y-2 text-xs font-mono text-zinc-500">
                                <li className="flex items-center gap-2"><span className="w-1 h-1 bg-emerald-500 rounded-full"></span> Edge Hardware Profiling</li>
                                <li className="flex items-center gap-2"><span className="w-1 h-1 bg-emerald-500 rounded-full"></span> Network Topology Mapping</li>
                                <li className="flex items-center gap-2"><span className="w-1 h-1 bg-emerald-500 rounded-full"></span> Latency Bottleneck Analysis</li>
                            </ul>
                        </div>
                    </motion.div>

                    {/* Security Clearances & Air-Gapped Verification */}
                    <motion.div variants={cardVariants} className="group flex flex-col p-8 rounded-2xl bg-[#0a0a0c] border border-white/5 hover:border-emerald-500/30 transition-all duration-500 h-full relative overflow-hidden shadow-[0_0_20px_rgba(0,0,0,0.5)]">
                        <div className="absolute top-0 right-0 w-32 h-32 bg-emerald-500/5 blur-[40px] rounded-full group-hover:bg-emerald-500/10 transition-colors duration-500"></div>
                        <div className="p-3 bg-zinc-900 border border-zinc-800 rounded-lg w-fit mb-6 relative z-10">
                            <Shield className="w-6 h-6 text-emerald-400" />
                        </div>
                        <h3 className="text-xl font-bold text-white mb-3 tracking-tight relative z-10">Data Sovereignty & Air-Gapped Security</h3>
                        <p className="text-zinc-400 text-sm leading-relaxed mb-6 flex-1 relative z-10">
                            True physical intelligence demands absolute data sovereignty. We design the cryptographic perimeter, configuring encrypted transfer protocols and establishing isolated, air-gapped data lakes engineered exclusively for secure model distillation. Our architectures pass rigorous penetration testing, ensuring highly guarded proprietary telemetry never breaches the physical boundary of the embedded device.
                        </p>
                        <div className="mt-auto pt-4 border-t border-white/5 relative z-10">
                            <ul className="space-y-2 text-xs font-mono text-zinc-500">
                                <li className="flex items-center gap-2"><span className="w-1 h-1 bg-emerald-500 rounded-full"></span> Cryptographic Inference Perimeters</li>
                                <li className="flex items-center gap-2"><span className="w-1 h-1 bg-emerald-500 rounded-full"></span> Localized Vector Databases</li>
                                <li className="flex items-center gap-2"><span className="w-1 h-1 bg-emerald-500 rounded-full"></span> Military-Grade Air-Gapping</li>
                            </ul>
                        </div>
                    </motion.div>

                    {/* Deterministic Stakeholder Alignment & Logic Schema */}
                    <motion.div variants={cardVariants} className="group flex flex-col p-8 rounded-2xl bg-[#0a0a0c] border border-white/5 hover:border-emerald-500/30 transition-all duration-500 h-full relative overflow-hidden shadow-[0_0_20px_rgba(0,0,0,0.5)]">
                        <div className="absolute top-0 right-0 w-32 h-32 bg-emerald-500/5 blur-[40px] rounded-full group-hover:bg-emerald-500/10 transition-colors duration-500"></div>
                        <div className="p-3 bg-zinc-900 border border-zinc-800 rounded-lg w-fit mb-6 relative z-10">
                            <Network className="w-6 h-6 text-emerald-400" />
                        </div>
                        <h3 className="text-xl font-bold text-white mb-3 tracking-tight relative z-10">Deterministic Logic Schemas</h3>
                        <p className="text-zinc-400 text-sm leading-relaxed mb-6 flex-1 relative z-10">
                            We align with your technical stakeholders to define absolute mathematical constraints and guard-railed logic schemas required for your specific physical application. We map exact operational boundaries, failure modes, and acceptable inference tolerances. This ensures the neural network behaves predictably without suffering from unconstrained hallucinatory drift.
                        </p>
                        <div className="mt-auto pt-4 border-t border-white/5 relative z-10">
                            <ul className="space-y-2 text-xs font-mono text-zinc-500">
                                <li className="flex items-center gap-2"><span className="w-1 h-1 bg-emerald-500 rounded-full"></span> Constrained Decoding Logic</li>
                                <li className="flex items-center gap-2"><span className="w-1 h-1 bg-emerald-500 rounded-full"></span> Output Verification Parsing</li>
                                <li className="flex items-center gap-2"><span className="w-1 h-1 bg-emerald-500 rounded-full"></span> State-Machine Integration</li>
                            </ul>
                        </div>
                    </motion.div>

                    {/* Multi-Phase Deployment & Hardened Shadow Rollout */}
                    <motion.div variants={cardVariants} className="group flex flex-col p-8 rounded-2xl bg-[#0a0a0c] border border-white/5 hover:border-emerald-500/30 transition-all duration-500 h-full relative overflow-hidden shadow-[0_0_20px_rgba(0,0,0,0.5)]">
                        <div className="absolute top-0 right-0 w-32 h-32 bg-emerald-500/5 blur-[40px] rounded-full group-hover:bg-emerald-500/10 transition-colors duration-500"></div>
                        <div className="p-3 bg-zinc-900 border border-zinc-800 rounded-lg w-fit mb-6 relative z-10">
                            <Server className="w-6 h-6 text-emerald-400" />
                        </div>
                        <h3 className="text-xl font-bold text-white mb-3 tracking-tight relative z-10">Shadow Rollout & Hardened Deployment</h3>
                        <p className="text-zinc-400 text-sm leading-relaxed mb-6 flex-1 relative z-10">
                            Our deployment protocol mitigates all operational risk. We initiate "Shadow Deployments," running quantized models securely in parallel to existing workflows, logging inferential reasoning without actuating physical consequence. We utilize these logs for aggressive A/B validation, tracking model drift or metric degradation prior to a full Hardened Rollout.
                        </p>
                        <div className="mt-auto pt-4 border-t border-white/5 relative z-10">
                            <ul className="space-y-2 text-xs font-mono text-zinc-500">
                                <li className="flex items-center gap-2"><span className="w-1 h-1 bg-emerald-500 rounded-full"></span> A/B Telemetry Tracking</li>
                                <li className="flex items-center gap-2"><span className="w-1 h-1 bg-emerald-500 rounded-full"></span> Zero-Downtime Quantization</li>
                                <li className="flex items-center gap-2"><span className="w-1 h-1 bg-emerald-500 rounded-full"></span> Model Drift Auditing</li>
                            </ul>
                        </div>
                    </motion.div>
                </motion.div>

                {/* Contact CTA */}
                <motion.div
                    initial={{ opacity: 0, scale: 0.95 }}
                    whileInView={{ opacity: 1, scale: 1 }}
                    transition={{ duration: 0.6 }}
                    viewport={{ once: true }}
                    className="mt-24 p-12 rounded-3xl bg-[#0a0a0c] border border-emerald-500/20 text-center relative overflow-hidden group shadow-[0_0_50px_rgba(16,185,129,0.05)]"
                >
                    <div className="absolute inset-0 bg-mesh-gradient opacity-10"></div>
                    <h2 className="text-3xl font-black text-white tracking-tight mb-4 relative z-10">Initiate Enterprise Intake</h2>
                    <p className="text-zinc-400 max-w-2xl mx-auto mb-8 relative z-10">
                        Clearances required for highly-classified infrastructure audits. Contact our principal architecture team to begin feasibility validation.
                    </p>
                    <Link href="/contact" className="inline-flex items-center gap-3 px-8 py-4 bg-emerald-500 hover:bg-emerald-400 text-[#09090b] font-bold rounded-xl transition-all shadow-[0_0_20px_rgba(16,185,129,0.3)] hover:shadow-[0_0_30px_rgba(16,185,129,0.5)] transform hover:scale-105 relative z-10">
                        <Lock className="w-5 h-5" /> Secure Request <ArrowRight className="w-5 h-5 ml-1" />
                    </Link>
                </motion.div>
            </section>

            {/* Enterprise Deployments (19 Clients) */}
            <section className="px-6 py-24 relative z-10 max-w-7xl mx-auto w-full border-t border-white/10">
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true, margin: "-100px" }}
                    transition={{ duration: 0.6 }}
                    className="mb-16"
                >
                    <div className="flex items-center gap-3 mb-4">
                        <Building2 className="w-5 h-5 text-emerald-400" />
                        <span className="text-xs font-bold uppercase tracking-[0.2em] text-emerald-400">Global Scale</span>
                    </div>
                    <h2 className="text-4xl font-bold tracking-tight text-white mb-6">
                        Enterprise Architecture Formations
                    </h2>
                    <p className="text-xl text-zinc-400 leading-relaxed max-w-3xl">
                        Apportunity Labs has a 16-year history of architecting foundational tier-1 infrastructure for the world&apos;s most demanding corporations. The following outlines 19 core applied engineering deployments.
                    </p>
                </motion.div>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {clients.map((client, i) => (
                        <motion.div
                            key={client.name}
                            initial={{ opacity: 0, scale: 0.95, y: 20 }}
                            whileInView={{ opacity: 1, scale: 1, y: 0 }}
                            viewport={{ once: true, margin: "-50px" }}
                            transition={{ duration: 0.5, delay: i * 0.05 }}
                            className="group flex flex-col gap-6 rounded-3xl border border-white/10 bg-white/5 p-8 transition-all hover:border-white/30 backdrop-blur-xl relative overflow-hidden"
                        >
                            <div className="h-12 w-auto max-w-[120px] filter saturate-0 opacity-70 group-hover:saturate-100 group-hover:opacity-100 transition-all duration-500 mb-2">
                                <img src={client.logo} alt={`Apportunity Labs SteelVision YOLOv10 Architecture - ${client.name} Deployment`} className="h-full w-full object-contain object-left" />
                            </div>
                            <div className="flex flex-col gap-3 relative z-10">
                                <h3 className="text-lg font-bold text-white leading-tight">{client.title}</h3>
                                <p className="text-sm text-zinc-400 leading-relaxed">
                                    {client.caseStudy}
                                </p>
                            </div>
                        </motion.div>
                    ))}
                </div>
            </section>
        </div>
    );
}
