'use client';

import { motion } from "framer-motion";
import { Network, Server, Database, ArrowLeft, Terminal as TerminalIcon, Building2 } from "lucide-react";
import { useState, useEffect } from "react";

// AI-Generated Enterprise Case Studies reflecting the new "Systems Architecture" context
const clients = [
    {
        name: "Apple",
        logo: "/clients/apple.svg",
        title: "Global Deployment Layer Tracking",
        caseStudy: "Developed deterministic on-device diagnostic frameworks and spatial engagement flows (SPEAR / Hubble). Bridged physical hardware with strictly segregated serverless cloud infrastructure across global enterprise campuses, handling massive concurrent telemetry."
    },
    {
        name: "Amazon",
        logo: "/clients/amazon.svg",
        title: "High-Scale Conversational Logistics",
        caseStudy: "Designed edge-native conversational bridges for warehouse automation. Optimized low-latency voice command inference models for immediate logistical routing, executing within stringent microsecond SLA constraints."
    },
    {
        name: "Walmart",
        logo: "/clients/walmart.svg",
        title: "Distributed Retail Systems",
        caseStudy: "Architected global logistics tracking systems capable of ingesting millions of synchronized telemetry requests per second. Migrated legacy inventory DBs to predictive ML pipelines to preempt supply chain bottlenecks."
    },
    {
        name: "Nike",
        logo: "/clients/nike.svg",
        title: "Real-Time Engagement Infrastructure",
        caseStudy: "Engineered scalable retail engagement grids. Synchronized local store Edge nodes with massive federated networks to process high-throughput transactional and behavioral data during high-stress peak events."
    },
    {
        name: "Southwest Airlines",
        logo: "/clients/southwest airlines.svg",
        title: "Flight Logistics Automation",
        caseStudy: "Developed predictive routing and crew scheduling optimization systems. Leveraged advanced operations research algorithms paired with real-time API integrations to minimize delay propagation across the national grid."
    },
    {
        name: "Verizon",
        logo: "/clients/verizon.svg",
        title: "Network Latency & Signal Prediction",
        caseStudy: "Built deep neural networks to predict cell tower congestion and auto-scale bandwidth allocations. Processed continuous streams of 5G telemetry data to ensure minimal packet loss for enterprise clients."
    },
    {
        name: "GE",
        logo: "/clients/ge.svg",
        title: "Industrial IoT Edge Inference",
        caseStudy: "Deployed optimized ML models directly onto heavy machinery sensors. Enabled real-time anomaly detection and predictive maintenance alerts without relying on continuous cloud connectivity."
    },
    {
        name: "Intuit",
        logo: "/clients/intuit.svg",
        title: "Financial LLM Data Structuring",
        caseStudy: "Architected secure data pipelines to parse unstructured financial records. Applied semantic search and Named Entity Recognition to automate tax categorization with ultra-high accuracy and absolute privacy compliance."
    },
    {
        name: "Oracle",
        logo: "/clients/oracle.svg",
        title: "Enterprise DB Optimization",
        caseStudy: "Integrated autonomous machine learning techniques to monitor query performance at scale. Built internal tooling that dynamically adjusted database indexing based on live traffic patterns."
    },
    {
        name: "Chase",
        logo: "/clients/chase.svg",
        title: "Fraud Detection Neural Architectures",
        caseStudy: "Designed graph-based neural networks to identify complex money-laundering topologies. Achieved sub-50ms transaction verification latency, safeguarding massive volumes of daily financial operations."
    },
    {
        name: "DirecTV",
        logo: "/clients/directv.svg",
        title: "Real-Time Content Analytics",
        caseStudy: "Engineered high-throughput streaming telemetry pipelines. Utilized collaborative filtering models to power real-time content recommendation engines for millions of simultaneous viewers."
    },
    {
        name: "Hyundai",
        logo: "/clients/hyundai.svg",
        title: "Connected Vehicle Telemetry",
        caseStudy: "Developed secure OTA (Over-The-Air) model update protocols. Processed continuous sensor fusion data generated by autonomous driving subsystems to improve fleet-wide object detection algorithms."
    },
    {
        name: "Volkswagen",
        logo: "/clients/volkswagen.svg",
        title: "Manufacturing Defect Computer Vision",
        caseStudy: "Deployed high-speed manufacturing line inspection systems. Utilized quantized Vision Transformers to detect micro-fractures in structural components with better-than-human reliability."
    },
    {
        name: "Panavision",
        logo: "/clients/panavision.svg",
        title: "Lens Calibration Automation",
        caseStudy: "Automated the precision calibration of cinematic lenses using computer vision. Built software that mapped chromatic aberration across complex glass elements to feed manufacturing corrections."
    },
    {
        name: "Technicolor",
        logo: "/clients/technicolor.svg",
        title: "Visual FX Rendering Pipelines",
        caseStudy: "Optimized massive GPU render farm allocations using predictive modeling. Reduced rendering bottlenecks for high-bandwidth cinematic sequences through intelligent distributed computing."
    },
    {
        name: "CBS",
        logo: "/clients/cbs.svg",
        title: "High-Throughput Media Distribution",
        caseStudy: "Architected resilient content delivery networks (CDNs) capable of handling unpredictable traffic spikes during live broadcast events. Implemented dynamic bitrate scaling to guarantee stream integrity."
    },
    {
        name: "KornFerry",
        logo: "/clients/kornferry.svg",
        title: "Applied NLP for Organizational Simulation",
        caseStudy: "Built sophisticated natural language processing tools to analyze executive communication patterns. Created simulated leadership scenarios powered by predictive behavioral models."
    },
    {
        name: "Vance and Hines",
        logo: "/clients/vance and hines.svg",
        title: "BLE 5.4 Edge Sensor Inference",
        caseStudy: "Developed low-latency Bluetooth Low Energy (BLE) bridges connecting high-performance motorcycle engine control units to mobile analytics dashboards for real-time race tuning."
    },
    {
        name: "Submission",
        logo: "/clients/submission.svg",
        title: "Multilingual Neural Intelligence",
        caseStudy: "Engineered entirely offline cross-lingual deterministic retrieval systems. Parsed massive ancient theological corpora using custom multi-modal embedding architectures for absolute fidelity."
    }
];

export default function Solutions() {
    const [typedText, setTypedText] = useState("");
    const fullJson = `{
  "status": "success",
  "latency": "142ms",
  "source": "Local_Vector_Store",
  "model": "Distilled-LVM-1.8B",
  "retrieval": {
    "top_k": 3,
    "semantic_score": 0.982,
    "context_chunk": "Section 4.2: Hardware calibration for BLE 5.4 synchronization..."
  },
  "spatial_verification": {
    "yolo_v10_detection": "active",
    "confidence": 0.994,
    "bounding_box": [102, 45, 304, 512]
  }
}`;

    useEffect(() => {
        let i = 0;
        const typingInterval = setInterval(() => {
            setTypedText(fullJson.slice(0, i));
            i++;
            if (i > fullJson.length) clearInterval(typingInterval);
        }, 15); // Fast typewriter effect
        return () => clearInterval(typingInterval);
    }, [fullJson]);

    return (
        <div className="relative flex min-h-screen flex-col overflow-x-hidden bg-[#09090b] text-slate-100 antialiased font-sans">

            {/* Navigation */}

            <section className="px-6 py-24 lg:py-32 relative z-10 max-w-6xl mx-auto w-full">
                <a href="/" className="inline-flex items-center gap-2 text-sm text-zinc-400 hover:text-emerald-400 mb-12 transition-colors">
                    <ArrowLeft className="w-4 h-4" /> Back to Home
                </a>

                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6 }}
                >
                    <span className="text-xs font-bold uppercase tracking-[0.2em] text-emerald-400 mb-4 block">Primary Project Case Study</span>
                    <h1 className="text-4xl md:text-6xl font-extrabold tracking-tight text-white mb-6">
                        Project SteelVision: Spatial Intelligence at the Edge.
                    </h1>
                    <p className="text-xl text-zinc-400 leading-relaxed max-w-4xl border-l-2 border-emerald-500/50 pl-6 mb-16">
                        <strong className="text-zinc-200">The Problem Space:</strong> Modern asset verification requires high-reliability spatial awareness, but cloud dependency introduces latency and privacy risks. Industrial and retail asset verification fails when the cloud is unavailable. Project SteelVision is our answer: a 100% offline-first Spatial Intelligence pipeline.
                    </p>
                </motion.div>

                <div className="grid grid-cols-1 lg:grid-cols-2 gap-16">
                    <motion.div
                        initial={{ opacity: 0, x: -20 }}
                        whileInView={{ opacity: 1, x: 0 }}
                        viewport={{ once: true }}
                        className="flex flex-col gap-12"
                    >
                        <div>
                            <h2 className="text-3xl font-bold tracking-tight text-white mb-8 border-b border-white/10 pb-4">The Architecture</h2>

                            <div className="flex flex-col gap-8">
                                <div className="flex gap-4">
                                    <div className="mt-1 flex-shrink-0 w-10 h-10 rounded-lg bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center text-emerald-400">
                                        <Server className="w-5 h-5" />
                                    </div>
                                    <div>
                                        <h3 className="text-lg font-bold text-white mb-2">Neural Pipeline</h3>
                                        <p className="text-zinc-400 leading-relaxed">A hybrid vision architecture utilizing <strong>YOLOv10</strong> for real-time object detection fused with <strong>Vision Transformers (ViT)</strong> for high-fidelity OCR.</p>
                                    </div>
                                </div>

                                <div className="flex gap-4">
                                    <div className="mt-1 flex-shrink-0 w-10 h-10 rounded-lg bg-blue-500/10 border border-blue-500/20 flex items-center justify-center text-blue-400">
                                        <Database className="w-5 h-5" />
                                    </div>
                                    <div>
                                        <h3 className="text-lg font-bold text-white mb-2">Local Intelligence</h3>
                                        <p className="text-zinc-400 leading-relaxed">An on-device RAG (Retrieval-Augmented Generation) system indexing 2M+ technical manual tokens for instant offline diagnostics.</p>
                                    </div>
                                </div>

                                <div className="flex gap-4">
                                    <div className="mt-1 flex-shrink-0 w-10 h-10 rounded-lg bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center text-emerald-400">
                                        <Network className="w-5 h-5" />
                                    </div>
                                    <div>
                                        <h3 className="text-lg font-bold text-white mb-2">Hardware Sync</h3>
                                        <p className="text-zinc-400 leading-relaxed">Direct sensor fusion via <strong>Bluetooth Low Energy (BLE 5.4)</strong> to synchronize physical asset states with digital twins in real-time.</p>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div className="p-8 rounded-3xl bg-white/5 border border-white/10 backdrop-blur-xl">
                            <h3 className="text-xl font-bold text-white mb-6">Technical Spec Sheet</h3>
                            <ul className="flex flex-col gap-4">
                                <li className="flex justify-between items-center border-b border-white/5 pb-4">
                                    <span className="text-zinc-500 font-mono text-sm">Inference Latency</span>
                                    <span className="text-emerald-400 font-bold">&lt;180ms on-device</span>
                                </li>
                                <li className="flex justify-between items-center border-b border-white/5 pb-4">
                                    <span className="text-zinc-500 font-mono text-sm">Model Architecture</span>
                                    <span className="text-white font-medium">1.8B parameter distilled VLM</span>
                                </li>
                                <li className="flex justify-between items-center pb-2">
                                    <span className="text-zinc-500 font-mono text-sm">Connectivity Protocol</span>
                                    <span className="text-white font-medium text-right">100% Offline-capable<br /><span className="text-xs text-zinc-500">w/ periodic Vector Store syncing</span></span>
                                </li>
                            </ul>
                        </div>
                    </motion.div>

                    <motion.div
                        initial={{ opacity: 0, x: 20 }}
                        whileInView={{ opacity: 1, x: 0 }}
                        viewport={{ once: true }}
                        className="flex flex-col gap-6"
                    >
                        {/* Mock RAG Terminal */}
                        <div className="rounded-2xl border border-white/10 bg-black/80 overflow-hidden shadow-2xl flex flex-col h-[550px]">
                            <div className="bg-white/5 border-b border-white/10 px-4 py-3 flex items-center gap-3">
                                <div className="flex gap-1.5">
                                    <div className="w-3 h-3 rounded-full bg-red-500/80"></div>
                                    <div className="w-3 h-3 rounded-full bg-yellow-500/80"></div>
                                    <div className="w-3 h-3 rounded-full bg-green-500/80"></div>
                                </div>
                                <div className="text-xs font-mono text-zinc-500 ml-4 flex items-center gap-2">
                                    <TerminalIcon className="w-3 h-3" />
                                    apportunity-edge-node ~ json-output
                                </div>
                            </div>

                            <div className="p-6 font-mono text-sm overflow-y-auto flex-1 text-zinc-300">
                                <div className="text-zinc-500 mb-2"># SteelVision Edge-RAG Response Metadata</div>
                                <div className="text-emerald-400 whitespace-pre-wrap leading-relaxed">
                                    {typedText}
                                    <span className="animate-pulse">_</span>
                                </div>
                            </div>
                        </div>
                    </motion.div>
                </div>
            </section>

            {/* Enterprise Deployments (19 Clients) */}
            <section className="px-6 py-24 relative z-10 max-w-7xl mx-auto w-full border-t border-white/10">
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true, margin: "-100px" }}
                    transition={{ duration: 0.6 }}
                    className="mb-16"
                >
                    <div className="flex items-center gap-3 mb-4">
                        <Building2 className="w-5 h-5 text-emerald-400" />
                        <span className="text-xs font-bold uppercase tracking-[0.2em] text-emerald-400">Global Scale</span>
                    </div>
                    <h2 className="text-4xl font-bold tracking-tight text-white mb-6">
                        Enterprise Architecture Formations
                    </h2>
                    <p className="text-xl text-zinc-400 leading-relaxed max-w-3xl">
                        Apportunity Labs has a 16-year history of architecting foundational tier-1 infrastructure for the world&apos;s most demanding corporations. The following outlines 19 core applied engineering deployments.
                    </p>
                </motion.div>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {clients.map((client, i) => (
                        <motion.div
                            key={client.name}
                            initial={{ opacity: 0, scale: 0.95, y: 20 }}
                            whileInView={{ opacity: 1, scale: 1, y: 0 }}
                            viewport={{ once: true, margin: "-50px" }}
                            transition={{ duration: 0.5, delay: i * 0.05 }}
                            className="group flex flex-col gap-6 rounded-3xl border border-white/10 bg-white/5 p-8 transition-all hover:border-white/30 backdrop-blur-xl relative overflow-hidden"
                        >
                            <div className="h-12 w-auto max-w-[120px] filter saturate-0 opacity-70 group-hover:saturate-100 group-hover:opacity-100 transition-all duration-500 mb-2">
                                <img src={client.logo} alt={`Apportunity Labs SteelVision YOLOv10 Architecture - ${client.name} Deployment`} className="h-full w-full object-contain object-left" />
                            </div>
                            <div className="flex flex-col gap-3 relative z-10">
                                <h3 className="text-lg font-bold text-white leading-tight">{client.title}</h3>
                                <p className="text-sm text-zinc-400 leading-relaxed">
                                    {client.caseStudy}
                                </p>
                            </div>
                        </motion.div>
                    ))}
                </div>
            </section>
        </div>
    );
}
