---
name: Build and Deploy Next.js App to GitHub Pages
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install and Build
      run: |
        npm ci
        npm run build

    - name: Deploy
      run: |
        git config --global user.name 'Suleman Imdad'
        git config --global user.email 'suleman.imdad@me.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}    
        npx gh-pages -d out -t -u "github-actions-bot <support+actions@github.com>"
